#!/usr/bin/env python3
"""
Folder Hierarchy Extractor for Document Classification System
Parses the Google Drive CSV and generates SQL to populate the folders table
"""

import csv
import os
from pathlib import Path
from collections import defaultdict
import uuid

# Configuration
CSV_FILE = "google_drive_documents.csv"
OUTPUT_SQL = "populate_folders.sql"

def parse_csv_and_extract_folders(csv_path: str) -> tuple[dict, dict]:
    """
    Parse CSV and extract folder hierarchy.
    
    Returns:
        tuple: (folders_dict, document_folders_dict)
            - folders_dict: {full_path: {name, parent_path, level}}
            - document_folders_dict: {document_title: full_folder_path}
    """
    folders = {}
    document_folders = {}
    
    print("[INFO] Reading CSV file...")
    
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            path = row.get('Path', '').strip()
            doc_name = row.get('Document Name', '').strip()
            
            if not path:
                continue
            
            # Check if path contains backslash (folder structure)
            if '\\' in path:
                # Extract folder path (everything before the last backslash)
                parts = path.split('\\')
                
                # The file is the last part
                # The folders are everything before
                folder_parts = parts[:-1]
                
                # Build folder hierarchy
                current_path = ""
                for i, folder_name in enumerate(folder_parts):
                    if current_path:
                        parent_path = current_path
                        current_path = f"{current_path}\\{folder_name}"
                    else:
                        parent_path = None
                        current_path = folder_name
                    
                    if current_path not in folders:
                        folders[current_path] = {
                            'name': folder_name,
                            'parent_path': parent_path,
                            'level': i
                        }
                
                # Map document to its folder
                document_folders[doc_name] = current_path
            else:
                # Document is in root (no folder)
                document_folders[doc_name] = None
    
    print(f"[SUCCESS] Extracted {len(folders)} unique folders")
    print(f"[SUCCESS] Mapped {len(document_folders)} documents to folders")
    
    return folders, document_folders

def generate_sql(folders: dict, document_folders: dict, output_path: str):
    """
    Generate SQL INSERT statements for folders and UPDATE statements for documents.
    """
    print(f"\n[INFO] Generating SQL file: {output_path}")
    
    # Sort folders by level to ensure parents are inserted before children
    sorted_folders = sorted(folders.items(), key=lambda x: x[1]['level'])
    
    # Generate UUIDs for each folder
    folder_uuids = {}
    for full_path, _ in sorted_folders:
        folder_uuids[full_path] = str(uuid.uuid4())
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("-- Auto-generated SQL for populating folders table\n")
        f.write("-- Generated by extract_folders.py\n")
        f.write("-- Run this script after creating the folders table\n\n")
        
        f.write("BEGIN;\n\n")
        
        # Insert folders
        f.write("-- Insert folder hierarchy\n")
        f.write("INSERT INTO folders (id, name, parent_id, full_path, level) VALUES\n")
        
        folder_inserts = []
        for full_path, folder_info in sorted_folders:
            folder_id = folder_uuids[full_path]
            name = folder_info['name'].replace("'", "''")  # Escape single quotes
            parent_id = folder_uuids.get(folder_info['parent_path'], None)
            parent_id_str = f"'{parent_id}'" if parent_id else "NULL"
            full_path_escaped = full_path.replace("'", "''")
            level = folder_info['level']
            
            folder_inserts.append(
                f"  ('{folder_id}', '{name}', {parent_id_str}, '{full_path_escaped}', {level})"
            )
        
        f.write(",\n".join(folder_inserts))
        f.write("\nON CONFLICT (full_path) DO NOTHING;\n\n")
        
        # Update documents with folder_id
        f.write("-- Update documents with folder references\n")
        f.write("-- This links each document to its folder\n\n")
        
        # Group documents by folder for more efficient updates
        folder_to_docs = defaultdict(list)
        root_docs = []
        
        for doc_name, folder_path in document_folders.items():
            if folder_path:
                folder_to_docs[folder_path].append(doc_name)
            else:
                root_docs.append(doc_name)
        
        update_count = 0
        for folder_path, doc_names in folder_to_docs.items():
            folder_id = folder_uuids.get(folder_path)
            if folder_id:
                folder_path_escaped = folder_path.replace("'", "''")
                f.write(f"-- Update documents in folder: {folder_path}\n")
                f.write(f"UPDATE documents SET folder_id = '{folder_id}' \n")
                f.write(f"WHERE path LIKE '{folder_path_escaped}\\%';\n\n")
                update_count += 1
        
        f.write(f"-- Total folder update statements: {update_count}\n")
        f.write(f"-- Total root documents (no folder): {len(root_docs)}\n\n")
        
        f.write("COMMIT;\n\n")
        f.write("-- Verify results\n")
        f.write("SELECT COUNT(*) as total_folders FROM folders;\n")
        f.write("SELECT COUNT(*) as documents_with_folders FROM documents WHERE folder_id IS NOT NULL;\n")
        f.write("SELECT COUNT(*) as documents_without_folders FROM documents WHERE folder_id IS NULL;\n")
    
    print(f"[SUCCESS] SQL file generated: {output_path}")
    print(f"   - Folders to insert: {len(folders)}")
    print(f"   - Folder update statements: {update_count}")
    print(f"   - Root documents (no folder): {len(root_docs)}")

def main():
    """Main execution function."""
    print("=" * 60)
    print("  Folder Hierarchy Extractor")
    print("  Document Classification System")
    print("=" * 60)
    print()
    
    # Get script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    csv_path = os.path.join(script_dir, CSV_FILE)
    output_path = os.path.join(script_dir, OUTPUT_SQL)
    
    # Check if CSV exists
    if not os.path.exists(csv_path):
        print(f"[ERROR] CSV file not found: {csv_path}")
        return
    
    # Parse CSV and extract folders
    folders, document_folders = parse_csv_and_extract_folders(csv_path)
    
    # Generate SQL
    generate_sql(folders, document_folders, output_path)
    
    print("\n" + "=" * 60)
    print("NEXT STEPS:")
    print("=" * 60)
    print("1. Run scripts/017_create_folders_table.sql in Supabase")
    print("2. Run scripts/018_add_folder_id_to_documents.sql in Supabase")
    print("3. Run temp/populate_folders.sql in Supabase")
    print("=" * 60)

if __name__ == "__main__":
    main()

